server:
  port: 8040

spring:
  datasource:
    url: jdbc:mysql://mysql-customer:3306/customerdb  # Docker container for mySQL
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    hostname: eureka-server # Docker service name
    prefer-ip-address: true   # <--- added this line
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

example:
  key: example-value
