server:
  port: 8020


spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: "mongodb://root:password@mongodb:20717/productdb?authSource=admin"  # Docker container running mongodb
      database: productdb

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    hostname: eureka-server # Docker service name
    prefer-ip-address: true   # <--- added this line
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

example:
  key: example-value
